# Generated by Django 2.2.2 on 2019-11-29 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myparliament', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='email',
            new_name='email1',
        ),
    ]
