# Generated by Django 2.2.2 on 2019-11-30 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myparliament', '0004_auto_20191130_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='email1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
