# Generated by Django 2.2.2 on 2019-11-30 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myparliament', '0005_auto_20191130_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='email1',
        ),
    ]
