# Generated by Django 2.2.2 on 2019-11-30 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myparliament', '0006_remove_application_email1'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='email1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
