# Generated by Django 2.2.2 on 2019-12-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myparliament', '0007_application_email1'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_step2_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='que1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='que2',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='application',
            name='que3',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
