# Generated by Django 2.2.2 on 2019-12-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myparliament', '0009_auto_20191202_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='que2',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='que3',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='que6',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='que7',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
    ]
