# Generated by Django 2.2.2 on 2019-12-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myparliament', '0010_auto_20191202_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_step4_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='que8',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='que9',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
    ]
